name: appsyncmarketplace
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: eu-west-1
  defaultAction: ALLOW
  userPoolId: !Ref CognitoUserPool
mappingTemplatesLocation: mapping-templates
mappingTemplates:
  # Queries
  - type: Query
    field: getMyProfile
    dataSource: usersTable
  - type: Query
    field: getProfile
    dataSource: usersTable
  - type: Query
    field: listCategories
    dataSource: categoryTable
  - type: Query
    field: listProducts
    dataSource: productsTable
  - type: Query
    field: getProduct
    dataSource: productsTable
  
  # Mutation
  - type: Mutation
    field: addCategory
    dataSource: categoryTable
  - type: Mutation
    field: updateCategory
    dataSource: categoryTable
  - type: Mutation
    field: deleteCategory
    dataSource: categoryTable
  - type: Mutation
    field: uploadProduct
    dataSource: uploadProductFunction
    request: false
    response: false
  - type: Mutation
    field: addReview
    dataSource: addReviewFunction
    request: false
    response: false

  # Nested Fields
  - type: Category
    field: creator
    dataSource: usersTable
    request: Category.creator.request.vtl
    response: Category.creator.response.vtl
  - type: Product
    field: uploader
    dataSource: usersTable
    request: Product.uploader.request.vtl
    response: Product.uploader.response.vtl
  - type: Product
    field: category
    dataSource: categoryTable
    request: Product.category.request.vtl
    response: Product.category.response.vtl
  - type: Product
    field: reviews
    dataSource: reviewsTable
    request: Product.reviews.request.vtl
    response: Product.reviews.response.vtl

dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config:
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: categoryTable
    config:
      tableName: !Ref CategoryTable
  - type: AMAZON_DYNAMODB
    name: productsTable
    config:
      tableName: !Ref ProductsTable
  - type: AMAZON_DYNAMODB
    name: reviewsTable
    config:
      tableName: !Ref ReviewsTable
  - type: AWS_LAMBDA
    name: uploadProductFunction
    config:
      functionName: uploadProduct
  - type: AWS_LAMBDA
    name: addReviewFunction
    config:
      functionName: addReview
 
substitutions:
  ReviewsTable: !Ref ReviewsTable